name: Build React + Vite

on:
  push:
    branches:
      - feature/landing-page

  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Verificar compilación
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependencias
        run: npm install

      - name: Construir proyecto
        run: npm run build

      - name: Build completado
        run: echo "✅ La aplicación React + Vite compiló correctamente."